# Totaling pipeline configuration

global:
  executable: "python3"
  cpu:
    processes: 1
    process-type: None
    threads-per-process: 1
    thread-type: None
  pre_exec: "pip install --upgrade pip; pip install numpy netCDF4 pyyaml"
  script: "total_workflow.py"
  arguments: 
    - "--directory"
    - "$RP_PILOT_STAGING/to_total/global/"
  options:
    - "nsamps"
    - "pyear_start"
    - "pyear_end"
    - "pyear_step"
    - "seed"
  upload_input_data:
    - './modules/total/total_workflow.py'
  download_output_data:
    - "total-workflow_globalsl.nc"


local:
  executable: "python3"
  cpu:
    processes: 1
    process-type: None
    threads-per-process: 1
    thread-type: None
  pre_exec: "pip install --upgrade pip; pip install numpy netCDF4 pyyaml"
  script: "total_workflow.py"
  arguments: 
    - "--local"
    - "--directory"
    - "$RP_PILOT_STAGING/to_total/local/"
  options:
    - "nsamps"
    - "pyear_start"
    - "pyear_end"
    - "pyear_step"
    - "seed"
  upload_input_data:
    - './modules/total/total_workflow.py'
  download_output_data:
    - "total-workflow_localsl.nc"