# ISMIP Emulated Ice Sheets Pipeline

pre-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml matplotlib; tar -xzf ipccar6_gmipemuglaciers_preprocess_data.tgz; rm ipccar6_gmipemuglaciers_preprocess_data.tgz"
    script: "ipccar6_preprocess_gmipemuglaciers.py"
    options:
      - "scenario"
      - "model_driver"
      - "baseyear"
      - "pipeline_id"
    upload_input_data:
      - "./modules/ipccar6/gmipemuglaciers/ipccar6_preprocess_gmipemuglaciers.py"
      - "./modules/ipccar6/gmipemuglaciers/import_data.py"
      - "./modules/ipccar6/gmipemuglaciers/filter_data.py"
      - "./modules/ipccar6/gmipemuglaciers/FindFAIRInputSamples.py"
      - "./modules/ipccar6/gmipemuglaciers/import_temp_data.py"
      - "./modules/ipccar6/gmipemuglaciers/filter_temp_data.py"
      - "./modules/ipccar6/gmipemuglaciers/Smooth.py"
      - "./modules/ipccar6/gmipemuglaciers/data/ipccar6_gmipemuglaciers_preprocess_data.tgz"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "ipccar6_fit_gmipemuglaciers.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - "./modules/ipccar6/gmipemuglaciers/ipccar6_fit_gmipemuglaciers.py"


project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "ipccar6_project_gmipemuglaciers.py"
    options:
      - "nsamps"
      - "replace"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - "./modules/ipccar6/gmipemuglaciers/ipccar6_project_gmipemuglaciers.py"
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    global_total_files:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_PEN_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

post-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ipccar6_gmipemuglaciers_postprocess_data.tgz; rm ipccar6_gmipemuglaciers_postprocess_data.tgz"
    script: "ipccar6_postprocess_gmipemuglaciers.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - './modules/ipccar6/gmipemuglaciers/ipccar6_postprocess_gmipemuglaciers.py'
      - './modules/ipccar6/gmipemuglaciers/read_locationfile.py'
      - './modules/ipccar6/gmipemuglaciers/AssignFP.py'
      - './modules/ipccar6/gmipemuglaciers/ReadFingerprint.py'
      - './modules/ipccar6/gmipemuglaciers/data/ipccar6_gmipemuglaciers_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_AIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
      - "%PIPELINE_ID%_AIS_localsl.nc"
