# FittedISMIP Ice Sheet Pipeline

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ipccar6_climate_data.tgz; rm ipccar6_climate_data.tgz; pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml matplotlib h5py xarray dask"
    script: "FittedISMIP_preprocess_icesheet.py"
    options:
      - "scenario"
      - "pipeline_id"
      - "tlm_data"
    upload_input_data:
      - "./modules/FittedISMIP/GrIS/FittedISMIP_preprocess_icesheet.py"
      - "./modules/FittedISMIP/GrIS/Import2lmData.py"
      - "./modules/FittedISMIP/GrIS/import_temp_data.py"
      - "./modules/FittedISMIP/GrIS/filter_temp_data.py"
      - "./modules/FittedISMIP/GrIS/data/ipccar6_climate_data.tgz"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf FittedISMIP_icesheet_fit_data.tgz; rm FittedISMIP_icesheet_fit_data.tgz"
    script: "FittedISMIP_fit_icesheet.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/FittedISMIP/GrIS/FittedISMIP_fit_icesheet.py'
      - "./modules/FittedISMIP/GrIS/data/FittedISMIP_icesheet_fit_data.tgz"


project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "FittedISMIP_project_icesheet.py"
    options:
      - "nsamps"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "crateyear_start"
      - "crateyear_end"
      - "seed"
      - "baseyear"
      - "pipeline_id"
    upload_input_data:
      - './modules/FittedISMIP/GrIS/FittedISMIP_project_icesheet.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      #- "%PIPELINE_ID%_EAIS_globalsl.nc"
      #- "%PIPELINE_ID%_WAIS_globalsl.nc"
      #- "%PIPELINE_ID%_PEN_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      #- "%PIPELINE_ID%_EAIS_globalsl.nc"
      #- "%PIPELINE_ID%_WAIS_globalsl.nc"
      #- "%PIPELINE_ID%_PEN_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf FittedISMIP_icesheet_postprocess_data.tgz; rm FittedISMIP_icesheet_postprocess_data.tgz"
    script: "FittedISMIP_postprocess_icesheet.py"
    options:
      - "chunksize"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - './modules/FittedISMIP/GrIS/FittedISMIP_postprocess_icesheet.py'
      - './modules/FittedISMIP/GrIS/read_locationfile.py'
      - './modules/FittedISMIP/GrIS/AssignFP.py'
      - './modules/FittedISMIP/GrIS/ReadFingerprint.py'
      - './modules/FittedISMIP/GrIS/data/FittedISMIP_icesheet_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      #- "%PIPELINE_ID%_AIS_localsl.nc"
      - "%PIPELINE_ID%_GIS_localsl.nc"
    download_output_data:
      #- "%PIPELINE_ID%_WAIS_localsl.nc"
      #- "%PIPELINE_ID%_EAIS_localsl.nc"
      #- "%PIPELINE_ID%_AIS_localsl.nc"
      - "%PIPELINE_ID%_GIS_localsl.nc"
