# FACTS dummy pipeline

preprocess:
  task1:
    executable: "python"
    script: "facts_dummy_preprocess.py"
    options:
      - "pipeline_id"
    #climate_output_data:
    #global_total_files:
    #local_total_files: