# IPCC AR6 Bamber Ice Sheets Pipeline

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ipccar6_bambericesheet_preprocess_data.tgz; rm ipccar6_bambericesheet_preprocess_data.tgz; pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml matplotlib"
    script: "ipccar6_preprocess_bambericesheet.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/ipccar6_preprocess_bambericesheet.py"
      - "%MODULE_PATH%/data/ipccar6_bambericesheet_preprocess_data.tgz"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "ipccar6_fit_bambericesheet.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ipccar6_fit_bambericesheet.py'


project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "ipccar6_project_bambericesheet.py"
    options:
      - "nsamps"
      - "seed"
      - "replace"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ipccar6_project_bambericesheet.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    global_total_files:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ipccar6_bambericesheet_postprocess_data.tgz; rm ipccar6_bambericesheet_postprocess_data.tgz"
    script: "ipccar6_postprocess_bambericesheet.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/ipccar6_postprocess_bambericesheet.py'
      - '%MODULE_PATH%/read_locationfile.py'
      - '%MODULE_PATH%/AssignFP.py'
      - '%MODULE_PATH%/ReadFingerprint.py'
      - '%MODULE_PATH%/data/ipccar6_bambericesheet_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
      - "%PIPELINE_ID%_AIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
      - "%PIPELINE_ID%_AIS_localsl.nc"
