# emulandice GrIS Pipeline

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml matplotlib"
    script: "emulandice_preprocess_GrIS.py"
    options:
      - "input_data_file"
      - "baseyear"
      - "pipeline_id"
    upload_input_data:
      - "./modules/emulandice/GrIS/emulandice_preprocess_GrIS.py"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "emulandice_fit_GrIS.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - "./modules/emulandice/GrIS/emulandice_fit_GrIS.py"



project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf emulandice_GrIS_project_data.tgz; rm emulandice_GrIS_project_data.tgz"
    script: "emulandice_project_GrIS.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - "./modules/emulandice/GrIS/emulandice_project_GrIS.py"
      - "./modules/emulandice/GrIS/data/emulandice_GrIS_project_data.tgz"
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_preprocess.pkl"
          - "FACTS_CLIMATE_FORCING_DATA.csv"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf emulandice_GrIS_postprocess_data.tgz; rm emulandice_GrIS_postprocess_data.tgz"
    script: "emulandice_postprocess_GrIS.py"
    options:
      - "locationfile"
      - "chunksize"
      - "pipeline_id"
    upload_input_data:
      - './modules/emulandice/GrIS/emulandice_postprocess_GrIS.py'
      - './modules/emulandice/GrIS/read_locationfile.py'
      - './modules/emulandice/GrIS/AssignFP.py'
      - './modules/emulandice/GrIS/ReadFingerprint.py'
      - './modules/emulandice/GrIS/data/emulandice_GrIS_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
