global-options:
    nsamps: 2000
    scenario: ssp585
    pyear_start: 2020
    pyear_end: 2150
    pyear_step: 10
    baseyear: 2005
    rcfg-name: "amarel"

climate_step:
    temperature:
        module_set: "fair"
        module: "temperature"
        generates_climate_output: true
#        input_data_file:
#              - "emissions.csv"
#        options:
#              rcmip_file: emissions.csv

sealevel_step:
    deconto21:
        module_set: "deconto21"
        module: "AIS"
        options:
            scenario: "rcp85"

    NZInsarGPS:
        module_set: "NZInsarGPS"
        module: "verticallandmotion"



