global-options:
    nsamps: 2000
    scenario: ssp585
    pyear_start: 2020
    pyear_end: 2300
    pyear_step: 10
    baseyear: 2005
    rcfg-name: "amarel"

climate_step:
    temperature:
        module_set: "fair"
        module: "temperature"
        generates_climate_output: true
    #    input_data_file:
            #  - "emissions.csv"
    #    options:
            #  rcmip_file: emissions.csv

sealevel_step:
    GrIS1f:
        module_set: "FittedISMIP"
        module: "GrIS"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"
            - "wf3f"
            - "wf1fnoVLM"
            - "wf2fnoVLM"
            - "wf3fnoVLM"
    deconto21:
        module_set: "deconto21"
        module: "AIS"
        include_in_workflow:
            - "wf3e"   
            - "wf3f"
            - "wf3enoVLM"   
            - "wf3fnoVLM"
        options:
            scenario: "rcp85"

    bamber19:
        module_set: "bamber19"
        module: "icesheets"
        include_in_workflow:
            - "wf4"
            - "wf4noVLM"
        options:
            scenario: "rcp85"

    emuAIS:
        module_set: "emulandice"
        module: "AIS"
        include_in_workflow:
            - "wf1e"
            - "wf1enoVLM"      
        options:
            pyear_end: 2100

    emuGrIS:
        module_set: "emulandice"
        module: "GrIS"
        include_in_workflow:
            - "wf1e"  
            - "wf2e"  
            - "wf3e"  
            - "wf1enoVLM"  
            - "wf2enoVLM"  
            - "wf3enoVLM"  
        options:
            pyear_end: 2100

    emuglaciers:
        module_set: "emulandice"
        module: "glaciers"
        include_in_workflow:
            - "wf1e"   
            - "wf2e"   
            - "wf3e"
            - "wf1enoVLM"   
            - "wf2enoVLM"   
            - "wf3enoVLM"
        options:
            pyear_end: 2100

    larmip:
        module_set: "larmip"
        module: "AIS"
        options_allowoverwrite:
            cyear_start: 2080
            cyear_end: 2100
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf2e"
            - "wf2f"
            - "wf2enoVLM"
            - "wf2fnoVLM"

    ar5glaciers:
        module_set: "ipccar5"
        module: "glaciers"
        options:
            gmip: 2
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"
            - "wf3f"
            - "wf4"
            - "wf1fnoVLM"
            - "wf2fnoVLM"
            - "wf3fnoVLM"
            - "wf4noVLM"
            
    ar5AIS:
        module_set: "ipccar5"
        module: "icesheets"
        pipeline_file: "pipeline.AIS.yml"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf1fnoVLM"

    ocean:
        module_set: "tlm"
        module: "sterodynamics"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf1e"
            - "wf2e"
            - "wf2f"
            - "wf3e"
            - "wf3f"
            - "wf4"
            - "wf1fnoVLM"
            - "wf1enoVLM"
            - "wf2enoVLM"
            - "wf2fnoVLM"
            - "wf3enoVLM"
            - "wf3fnoVLM"
            - "wf4noVLM"

    NZInsarGPS:
        module_set: "NZInsarGPS"
        module: "verticallandmotion"
        include_in_workflow:
            - "wf1f"
            - "wf1e"
            - "wf2e"
            - "wf2f"
            - "wf3e"
            - "wf3f"
            - "wf4"

    lws:
        module_set: "ssp"
        module: "landwaterstorage"
        options:
            scenario: "ssp5"
            dcrate_lo: -0.4
        include_in_workflow:
            - "wf1f"
            - "wf1e"
            - "wf2e"
            - "wf2f"
            - "wf3e"
            - "wf3f"
            - "wf4"
            - "wf1fnoVLM"
            - "wf1enoVLM"
            - "wf2enoVLM"
            - "wf2fnoVLM"
            - "wf3enoVLM"
            - "wf3fnoVLM"
            - "wf4noVLM"

totaling_step:
    total:
        module_set: "facts"
        module: "total"
        loop_over_workflows: true
        loop_over_scales: true
        stages:
            - workflow