global-options:
    nsamps: 2000
    scenario: ssp245
    pyear_start: 2020
    pyear_end: 2300
    pyear_step: 10
    baseyear: 2005
    rcfg-name: "amarel"

climate_step:
    temperature:
        module_set: "fair"
        module: "temperature"
        generates_climate_output: true
#        input_data_file:
#              - "emissions.csv"
#        options:
#              rcmip_file: emissions.csv

sealevel_step:
    GrIS1f:
        module_set: "FittedISMIP"
        module: "GrIS"
        include_in_workflow:
            - "wf1f"
            - "wf2f"
            - "wf3f"
            - "wf1fNOVLM"
            - "wf2fNOVLM"
            - "wf3fNOVLM"

    deconto21:
        module_set: "deconto21"
        module: "AIS"
        include_in_workflow:
            - "wf3e"   
            - "wf3f"
            - "wf3eNOVLM"   
            - "wf3fNOVLM"

    bamber19:
        module_set: "bamber19"
        module: "icesheets"
        include_in_workflow:
            - "wf4" 
            - "wf4NOVLM" 

    emuAIS:
        module_set: "emulandice"
        module: "AIS"
        include_in_workflow:
            - "wf1e"
            - "wf1eNOVLM"      
        options:
            pyear_end: 2100

    emuGrIS:
        module_set: "emulandice"
        module: "GrIS"
        include_in_workflow:
            - "wf1e"  
            - "wf2e"  
            - "wf3e"
            - "wf1eNOVLM"  
            - "wf2eNOVLM"  
            - "wf3eNOVLM"  
        options:
            pyear_end: 2100

    emuglaciers:
        module_set: "emulandice"
        module: "glaciers"
        include_in_workflow:
            - "wf1e"   
            - "wf2e"   
            - "wf3e"
            - "wf1eNOVLM"   
            - "wf2eNOVLM"   
            - "wf3eNOVLM"
        options:
            pyear_end: 2100

    larmip:
        module_set: "larmip"
        module: "AIS"
        include_in_workflow:
            - "wf2e"
            - "wf2f"
            - "wf2eNOVLM"
            - "wf2fNOVLM"

    ar5glaciers:
        module_set: "ipccar5"
        module: "glaciers"
        options:
            gmip: 2
        include_in_workflow:
            - "wf1f"
            - "wf2f"
            - "wf3f"
            - "wf4"
            - "wf1fNOVLM"
            - "wf2fNOVLM"
            - "wf3fNOVLM"
            - "wf4NOVLM"

    ar5AIS:
        module_set: "ipccar5"
        module: "icesheets"
        pipeline_file: "pipeline.AIS.yml"
        include_in_workflow:
            - "wf1f"
            - "wf1fNOVLM"

    ocean:
        module_set: "tlm"
        module: "sterodynamics"
        include_in_workflow:
            - "wf1f"
            - "wf1e"
            - "wf2e"
            - "wf2f"
            - "wf3e"
            - "wf3f"
            - "wf4"
            - "wf1fNOVLM"
            - "wf1eNOVLM"
            - "wf2eNOVLM"
            - "wf2fNOVLM"
            - "wf3eNOVLM"
            - "wf3fNOVLM"
            - "wf4NOVLM"

    InSAR:
        module_set: "InSAR"
        module: "verticallandmotion"
        include_in_workflow:
            - "wf1f"
            - "wf1e"
            - "wf2e"
            - "wf2f"
            - "wf3e"
            - "wf3f"
            - "wf4"

    lws:
        module_set: "ssp"
        module: "landwaterstorage"
        options:
            dcrate_lo: -0.4
        include_in_workflow:
            - "wf1f"
            - "wf1e"
            - "wf2e"
            - "wf2f"
            - "wf3e"
            - "wf3f"
            - "wf4"
            - "wf1fNOVLM"
            - "wf1eNOVLM"
            - "wf2eNOVLM"
            - "wf2fNOVLM"
            - "wf3eNOVLM"
            - "wf3fNOVLM"
            - "wf4NOVLM"

totaling_step:
    total:
        module_set: "facts"
        module: "total"
        loop_over_workflows: true
        loop_over_scales: true
        stages:
            - workflow

#esl_step:
#    extremesealevel:
#        loop_over_workflows: true
#        module_set: "extremesealevel"
#        module: "pointsoverthreshold"
#        options:
#            target_years: 2050,2100
#            total_localsl_file: "$SHARED/totaled/%EXPERIMENT_NAME%.total.workflow.%WORKFLOW_NAME%.local.nc" 
