# Kopp14 Thermal Expansion Pipeline

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    python_dependencies: "numpy"
    script: "kopp14_preprocess_thermalexp.py"
    options:
      - "scenario"
      - "model_dir"
      - "no_drift_corr"
      - "pipeline_id"
    upload_input_data:
      - "%MODULE_PATH%/kopp14_preprocess_thermalexp.py"
      - "%MODULE_PATH%/IncludeModels.py"
      - "%MODULE_PATH%/SmoothZOSTOGA.py"
      - "%MODULE_PATH%/DriftCorr.py"
      - "%MODULE_PATH%/Smooth.py"
      - "%MODULE_PATH%/read_CSIRO.py"
      - "%MODULE_PATH%/readMarzeion.py"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/data/kopp14_thermalexp_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_config.pkl"
#      - "%PIPELINE_ID%_ZOSTOGA.pkl"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "kopp14_fit_thermalexp.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/kopp14_fit_thermalexp.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOSTOGA.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"


project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "kopp14_project_thermalexp.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/kopp14_project_thermalexp.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    script: "kopp14_postprocess_thermalexp.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/kopp14_postprocess_thermalexp.py'
      - '%MODULE_PATH%/read_locationfile.py'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"