# Kopp14 Thermal Expansion Pipeline

pre-process:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf kopp14_thermalexp_data.tgz; pip install numpy"
    script: "kopp14_preprocess_thermalexp.py"
    options:
      - "scenario"
      - "model_dir"
      - "no_drift_corr"
    upload_input_data:
      - "./modules/kopp14/thermalexpansion/kopp14_preprocess_thermalexp.py"
      - "./modules/kopp14/thermalexpansion/IncludeModels.py"
      - "./modules/kopp14/thermalexpansion/SmoothZOSTOGA.py"
      - "./modules/kopp14/thermalexpansion/DriftCorr.py"
      - "./modules/kopp14/thermalexpansion/Smooth.py"
      - "./modules/kopp14/thermalexpansion/read_CSIRO.py"
      - "./modules/kopp14/thermalexpansion/readMarzeion.py"
      - "./modules/kopp14/thermalexpansion/data/kopp14_thermalexp_data.tgz"
#    download_output_data:
#      - "kopp14_thermalexp_config.pkl"
#      - "kopp14_thermalexp_ZOSTOGA.pkl"


fit:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "kopp14_fit_thermalexp.py"
    options:
      - "config_file"
      - "zostoga_file"
    upload_input_data:
      - './modules/kopp14/thermalexpansion/kopp14_fit_thermalexp.py'
    copy_input_data:
      pre-process:
        task1:
          - "kopp14_thermalexp_config.pkl"
          - "kopp14_thermalexp_ZOSTOGA.pkl"
#    download_output_data:
#      - "kopp14_thermalexp_fit.pkl"


project:
  task1:
    executable: "python"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "kopp14_project_thermalexp.py"
    options:
      - "nsamps"
      - "seed"
      - "config_file"
      - "fit_file"
    upload_input_data:
      - './modules/kopp14/thermalexpansion/kopp14_project_thermalexp.py'
    copy_input_data:
      pre-process:
        task1:
          - "kopp14_thermalexp_config.pkl"
      fit:
        task1:
          - "kopp14_thermalexp_fit.pkl"
    download_output_data:
      - "kopp14_thermalexp_projections.pkl"