# Kopp14 Ocean Dynamics Pipeline

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf kopp14_oceandynamics_data.tgz; rm kopp14_oceandynamics_data.tgz; pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml h5py"
    script: "kopp14_preprocess_oceandynamics.py"
    options:
      - "scenario"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/kopp14_preprocess_oceandynamics.py"
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/IncludeModels.py"
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/IncludeDABZOSModels.py"
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/SmoothZOSTOGA.py"
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/DriftCorr.py"
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/Smooth.py"
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/read_locationfile.py"
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/read_CSIRO.py"
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/readMarzeion.py"
      - "./modules/%MODULE_SET_NAME%/%MODULE_NAME%/data/kopp14_oceandynamics_data.tgz"
    copy_shared_data:
      - '$SHARED/location.lst'
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "kopp14_fit_oceandynamics.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/%MODULE_SET_NAME%/%MODULE_NAME%/kopp14_fit_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOSTOGA.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"

project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "kopp14_project_oceandynamics.py"
    options:
      - "pipeline_id"
      - "nsamps"
      - "seed"
    upload_input_data:
      - './modules/%MODULE_SET_NAME%/%MODULE_NAME%/kopp14_project_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "kopp14_postprocess_oceandynamics.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - './modules/%MODULE_SET_NAME%/%MODULE_NAME%/kopp14_postprocess_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
          - "%PIPELINE_ID%_oceandynamics_fit.pkl"
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
