# AR5 Glaciers Pipeline

pre-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ar5_glaciers_preprocess_data.tgz; pip3 install --upgrade pip3; pip3 install numpy scipy netCDF4 pyyaml matplotlib"
    script: "ar5_preprocess_glaciers.py"
    options:
      - "scenario"
      - "pipeline_id"
    upload_input_data:
      - "./modules/ar5/glaciers/ar5_preprocess_glaciers.py"
      - "./modules/ar5/glaciers/data/ar5_glaciers_preprocess_data.tgz"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"

fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "ar5_fit_glaciers.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/ar5/glaciers/ar5_fit_glaciers.py'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_data.pkl"
#    download_output_data:
#      - "%PIPELINE_ID%_fit.pkl"

project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ar5_glaciers_project_data.tgz"
    script: "ar5_project_glaciers.py"
    options:
      - "nmsamps"
      - "ntsamps"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - './modules/ar5/glaciers/ar5_project_glaciers.py'
      - './modules/ar5/glaciers/data/ar5_glaciers_project_data.tgz'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_data.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"


post-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ar5_glaciers_postprocess_data.tgz"
    script: "ar5_postprocess_glaciers.py"
    options:
      - "site_ids"
      - "pipeline_id"
    upload_input_data:
      - './modules/ar5/glaciers/ar5_postprocess_glaciers.py'
      - './modules/ar5/glaciers/read_bkgdrate.py'
      - './modules/ar5/glaciers/AssignFP.py'
      - './modules/ar5/glaciers/ReadFingerprint.py'
      - './modules/ar5/glaciers/data/ar5_glaciers_postprocess_data.tgz'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_data.pkl"
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
