# Kopp14 Vertical Land Motion Pipeline

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml"
    script: "kopp14_preprocess_verticallandmotion.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - "./modules/kopp14/verticallandmotion/kopp14_preprocess_verticallandmotion.py"
      - "./modules/kopp14/verticallandmotion/data/bkgdrate.tsv"
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "kopp14_fit_verticallandmotion.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/kopp14/verticallandmotion/kopp14_fit_verticallandmotion.py'


project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "kopp14_project_verticallandmotion.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/kopp14/verticallandmotion/kopp14_project_verticallandmotion.py'

postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "kopp14_postprocess_verticallandmotion.py"
    options:
      - "nsamps"
      - "seed"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - './modules/kopp14/verticallandmotion/kopp14_postprocess_verticallandmotion.py'
      - './modules/kopp14/verticallandmotion/read_locationfile.py'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
