global-options:
    nsamps: 2000
    scenario: ssp585
    pyear_start: 2020
    pyear_end: 2150
    pyear_step: 10
    baseyear: 2005
    
sealevel_step:
    NZInsarGPS1:
        module_set: "NZInsarGPS1"
        module: "verticallandmotion"




# sealevel_step:
#     k14vlm:
#         module_set: "kopp14"
#         module: "verticallandmotion"

#     NZInsarGPS:
#         module_set: "NZInsarGPS"
#         module: "verticallandmotion"