# Two-layer Model Ocean Dynamics Pipeline
# modified from the Kopp14 pipeline.yml, needs  to be examined

preprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ipccar6_climate_data.tgz ; tar -xzf tlm_oceandynamics_preprocess.tgz; tar -xzf tlm_oceandynamics_cmip6.tgz; rm ipccar6_climate_data.tgz tlm_oceandynamics_preprocess.tgz tlm_oceandynamics_cmip6.tgz; pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml h5py"
    script: "tlm_preprocess_oceandynamics.py"
    options:
      - "scenario"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "locationfile"
      - "pipeline_id"
      - "model_dir"
      - "no_drift_corr"
      - "no_correlation"
    upload_input_data:
      - "./modules/tlm/oceandynamics/tlm_preprocess_oceandynamics.py"
      - "./modules/tlm/oceandynamics/Import2lmData.py"
      - "./modules/tlm/oceandynamics/IncludeCMIP6Models.py"
      - "./modules/tlm/oceandynamics/IncludeCMIP6ZOSModels.py"
      - "./modules/tlm/oceandynamics/SmoothZOSTOGA.py"
      - "./modules/tlm/oceandynamics/Smooth.py"
      - "./modules/tlm/oceandynamics/read_locationfile.py"
      - "./modules/tlm/oceandynamics/read_CSIRO.py"
      - "./modules/tlm/oceandynamics/readMarzeion.py"
      - "./modules/tlm/oceandynamics/data/tlm_oceandynamics_preprocess.tgz"
      - "./modules/tlm/oceandynamics/data/tlm_oceandynamics_cmip6.tgz"
      - "./modules/tlm/oceandynamics/data/ipccar6_climate_data.tgz"
    copy_shared_data:
      - '$SHARED/location.lst'
#    download_output_data:
#      - "%PIPELINE_ID%_data.pkl"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "tlm_fit_oceandynamics.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/tlm/oceandynamics/tlm_fit_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOSTOGA.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"

project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "tlm_project_oceandynamics.py"
    options:
      - "pipeline_id"
      - "nsamps"
      - "seed"
      - "tlm"
    upload_input_data:
      - './modules/tlm/oceandynamics/tlm_project_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: []
    script: "tlm_postprocess_oceandynamics.py"
    options:
      - "nsamps"
      - "seed"
      - "pipeline_id"
      - "chunksize"
      - "keep_temp"
    upload_input_data:
      - './modules/tlm/oceandynamics/tlm_postprocess_oceandynamics.py'
    copy_input_data:
      preprocess:
        task1:
          - "%PIPELINE_ID%_config.pkl"
          - "%PIPELINE_ID%_ZOS.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_thermalexp_fit.pkl"
          - "%PIPELINE_ID%_oceandynamics_fit.pkl"
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_localsl.nc"
