# emulandice AIS Pipeline

project:
  task1:
    executable: "python3"
    python_dependencies: "numpy scipy netCDF4 pyyaml matplotlib xarray dask"
    script: "emulandice_AIS_project.py"
    options:
      - "pipeline_id"
      - "scenario"
      - "climate_data_file"
      - "nsamps"
      - "baseyear"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "seed"
      - "cyear_start"
      - "cyear_end"
    upload_input_data:
      - "%MODULE_PATH%/../shared/emulandice_environment.sh"
      - "%MODULE_PATH%/../shared/emulandice_steer.sh"
    upload_and_extract_input_data:
      - "%MODULE_PATH%/../shared/emulandice_bundled_dependencies.tgz"
    global_total_files:
      - "%PIPELINE_ID%_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_PEN_globalsl.nc"

postprocess:
  task1:
    executable: "python3"
    script: "emulandice_AIS_postprocess.py"
    options:
      - "locationfile"
      - "chunksize"
      - "pipeline_id"
    upload_input_data:
      - '%MODULE_PATH%/../shared/read_locationfile.py'
      - '%MODULE_PATH%/../shared/AssignFP.py'
      - '%MODULE_PATH%/../shared/ReadFingerprint.py'
    upload_and_extract_input_data:
      - 'grd_fingerprints_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
