# FittedISMIP Ice Sheets Pipeline

pre-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf FittedISMIP_icesheets_preprocess_data.tgz; rm FittedISMIP_icesheets_preprocess_data.tgz; pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml matplotlib h5py"
    script: "FittedISMIP_preprocess_icesheets.py"
    options:
      - "scenario"
      - "pipeline_id"
      - "tlm_data"
    upload_input_data:
      - "./modules/FittedISMIP/icesheets/FittedISMIP_preprocess_icesheets.py"
      - "./modules/FittedISMIP/icesheets/Import2lmData.py"
      - "./modules/FittedISMIP/icesheets/import_temp_data.py"
      - "./modules/FittedISMIP/icesheets/filter_temp_data.py"
      - "./modules/FittedISMIP/icesheets/data/FittedISMIP_icesheets_preprocess_data.tgz"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf FittedISMIP_icesheets_fit_data.tgz; rm FittedISMIP_icesheets_fit_data.tgz"
    script: "FittedISMIP_fit_icesheets.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/FittedISMIP/icesheets/FittedISMIP_fit_icesheets.py'
      - "./modules/FittedISMIP/icesheets/data/FittedISMIP_icesheets_fit_data.tgz"


project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "FittedISMIP_project_icesheets.py"
    options:
      - "nsamps"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "seed"
      - "baseyear"
      - "pipeline_id"
    upload_input_data:
      - './modules/FittedISMIP/icesheets/FittedISMIP_project_icesheets.py'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_data.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_PEN_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_PEN_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

post-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf FittedISMIP_icesheets_postprocess_data.tgz; rm FittedISMIP_icesheets_postprocess_data.tgz"
    script: "FittedISMIP_postprocess_icesheets.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - './modules/FittedISMIP/icesheets/FittedISMIP_postprocess_icesheets.py'
      - './modules/FittedISMIP/icesheets/read_locationfile.py'
      - './modules/FittedISMIP/icesheets/AssignFP.py'
      - './modules/FittedISMIP/icesheets/ReadFingerprint.py'
      - './modules/FittedISMIP/icesheets/data/FittedISMIP_icesheets_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_AIS_localsl.nc"
      - "%PIPELINE_ID%_GIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
      - "%PIPELINE_ID%_AIS_localsl.nc"
      - "%PIPELINE_ID%_GIS_localsl.nc"
