global-options:
    nsamps: 2000
    scenario: ssp370
    pyear_start: 2020
    pyear_end: 2300
    pyear_step: 10
    baseyear: 2005
    rcfg-name: "amarel"

climate_step:
    temperature:
        module_set: "fair"
        module: "temperature"
        generates_climate_output: true
    #    input_data_file:
            #  - "emissions.csv"
    #    options:
            #  rcmip_file: emissions.csv

sealevel_step:
    GrIS1f:
        module_set: "FittedISMIP"
        module: "GrIS"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"
            - "wf1fNOVLM"
            - "wf2fNOVLM"

    emuAIS:
        module_set: "emulandice"
        module: "AIS"
        include_in_workflow:
            - "wf1e"
            - "wf1eNOVLM"      
        options:
            pyear_end: 2100

    emuGrIS:
        module_set: "emulandice"
        module: "GrIS"
        include_in_workflow:
            - "wf1e"  
            - "wf2e"
            - "wf1eNOVLM"  
            - "wf2eNOVLM"  
        options:
            pyear_end: 2100

    emuglaciers:
        module_set: "emulandice"
        module: "glaciers"
        include_in_workflow:
            - "wf1e"   
            - "wf2e"
            - "wf1eNOVLM"   
            - "wf2eNOVLM"   
        options:
            pyear_end: 2100

    larmip:
        module_set: "larmip"
        module: "AIS"
        options: 
            cyear_start: 2080
            cyear_end: 2100
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf2e"
            - "wf2f"
            - "wf2eNOVLM"
            - "wf2fNOVLM"

    ar5glaciers:
        module_set: "ipccar5"
        module: "glaciers"
        options:
            gmip: 2
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"
            - "wf1fNOVLM"
            - "wf2fNOVLM"

    ar5AIS:
        module_set: "ipccar5"
        module: "icesheets"
        pipeline_file: "pipeline.AIS.yml"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf1fNOVLM"

    ocean:
        module_set: "tlm"
        module: "sterodynamics"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf1e"
            - "wf2e"
            - "wf2f"
            - "wf1fNOVLM"
            - "wf1eNOVLM"
            - "wf2eNOVLM"
            - "wf2fNOVLM"

    NZInsarGPS1:
        module_set: "NZInsarGPS1"
        module: "verticallandmotion"
        include_in_workflow:
            - "wf1f"
            - "wf1e"
            - "wf2e"
            - "wf2f"

    lws:
        module_set: "ssp"
        module: "landwaterstorage"
        options:
            scenario: "ssp3"
            dcrate_lo: -0.4
        include_in_workflow:
            - "wf1f"
            - "wf1e"
            - "wf2e"
            - "wf2f"
            - "wf1fNOVLM"
            - "wf1eNOVLM"
            - "wf2eNOVLM"
            - "wf2fNOVLM"

totaling_step:
    total:
        module_set: "facts"
        module: "total"
        loop_over_workflows: true
        loop_over_scales: true
        stages:
            - workflow