global-options:
    nsamps: 2000
    scenario: rcp85
    pyear_start: 2020
    pyear_end: 2150
    pyear_step: 10
    baseyear: 2005
    rcfg-name: "amarel"
    
sealevel_step:
    deconto16:
        module_set: "deconto16"
        module: "AIS"



