global-options:
    nsamps: 2000
    scenario: ssp585
    pyear_start: 2020
    pyear_end: 2150
    pyear_step: 10
    baseyear: 2005
    rcfg-name: "amarel"

climate_step:
    temperature:
        module_set: "fair"
        module: "temperature"
        generates_climate_output: true
    #    input_data_file:
            #  - "emissions.csv"
    #    options:
            #  rcmip_file: emissions.csv

sealevel_step:
    # GrIS1f:
    #     module_set: "FittedISMIP"
    #     module: "GrIS"
    #     options_allowoverwrite:
    #         climate_data_file: "%CLIMATE_DATA_FILE%"
    #     include_in_workflow:
    #         - "wf1f"
    #         - "wf2f"
    #         - "wf3f"


    ar5glaciers:
        module_set: "ipccar5"
        module: "glaciers"
        options:
            gmip: 2
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"
            - "wf3f"
            - "wf4"