# AR5 Ice Sheets Pipeline

pre-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ar5_icesheets_preprocess_data.tgz; rm ar5_icesheets_preprocess_data.tgz; pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml matplotlib"
    script: "ar5_preprocess_icesheets.py"
    options:
      - "scenario"
      - "pipeline_id"
      - "baseyear"
    upload_input_data:
      - "./modules/ar5/icesheets/ar5_preprocess_icesheets.py"
      - "./modules/ar5/icesheets/data/ar5_icesheets_preprocess_data.tgz"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "ar5_fit_icesheets.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/ar5/icesheets/ar5_fit_icesheets.py'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_data.pkl"


project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ar5_icesheets_project_data.tgz; rm ar5_icesheets_project_data.tgz"
    script: "ar5_project_icesheets.py"
    options:
      - "nmsamps"
      - "ntsamps"
      - "nsamps"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "seed"
      - "pipeline_id"
    upload_input_data:
      - './modules/ar5/icesheets/ar5_project_icesheets.py'
      - './modules/ar5/icesheets/data/ar5_icesheets_project_data.tgz'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_data.pkl"
      fit:
        task1:
          - "%PIPELINE_ID%_fit.pkl"
    global_total_files:
      - "%PIPELINE_ID%_TIS_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_globalsl.nc"
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
      - "%PIPELINE_ID%_TIS_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

post-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf ar5_icesheets_postprocess_data.tgz; rm ar5_icesheets_postprocess_data.tgz"
    script: "ar5_postprocess_icesheets.py"
    options:
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - './modules/ar5/icesheets/ar5_postprocess_icesheets.py'
      - './modules/ar5/icesheets/read_locationfile.py'
      - './modules/ar5/icesheets/AssignFP.py'
      - './modules/ar5/icesheets/ReadFingerprint.py'
      - './modules/ar5/icesheets/data/ar5_icesheets_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_GIS_localsl.nc"
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
