global-options:
    nsamps: 200
    scenario: ssp119
    pyear_start: 2020
    pyear_end: 2150
    pyear_step: 10
    baseyear: 2005
    rcfg-name: "amarel"

climate_step:
    temperature:
        module_set: "fair"
        module: "temperature"
        generates_climate_output: true
#       input_data_file:
#             - "emissions.csv"
#       options:
#             rcmip_file: emissions.csv

sealevel_step:
    GrIS1f:
        module_set: "FittedISMIP"
        module: "GrIS"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    larmip:
        module_set: "larmip"
        module: "AIS"
        options_allowoverwrite:
           climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf2f"

    ar5glaciers:
        module_set: "ipccar5"
        module: "glaciers"
        options:
            gmip: 2
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    ar5AIS:
        module_set: "ipccar5"
        module: "icesheets"
        pipeline_file: "pipeline.AIS.yml"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"

    ocean:
        module_set: "tlm"
        module: "sterodynamics"
        options_allowoverwrite:
            climate_data_file: "%CLIMATE_DATA_FILE%"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    NZInsarGPS:
        module_set: "NZInsarGPS"
        module: "verticallandmotion"
        include_in_workflow:
            - "wf1f"
            - "wf2f"

    lws:
        module_set: "ssp"
        module: "landwaterstorage"
        options:
            scenario: "ssp1"
            dcrate_lo: -0.4
        include_in_workflow:
            - "wf1f"
            - "wf2f"

totaling_step:
    total:
        module_set: "facts"
        module: "total"
        loop_over_workflows: true
        loop_over_scales: true
        stages:
            - workflow


# esl_step:
#     extremesealevel:
#         loop_over_workflows: true
#         module_set: "extremesealevel"
#         module: "pointsoverthreshold"
#         options:
#             target_years: 2050,2100
#             total_localsl_file: "$SHARED/totaled/%EXPERIMENT_NAME%.total.workflow.%WORKFLOW_NAME%.local.nc" 