# dp21 Ice Sheets Pipeline

pre-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf dp21_icesheet_preprocess_data.tgz; rm dp21_icesheet_preprocess_data.tgz; pip install --upgrade pip; pip install numpy scipy netCDF4 pyyaml matplotlib xarray dask"
    script: "dp21_preprocess_icesheet.py"
    options:
      - "scenario"
      - "pipeline_id"
      - "baseyear"
    upload_input_data:
      - "./modules/dp21/icesheet/dp21_preprocess_icesheet.py"
      - "./modules/dp21/icesheet/data/dp21_icesheet_preprocess_data.tgz"


fit:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "dp21_fit_icesheet.py"
    options:
      - "pipeline_id"
    upload_input_data:
      - './modules/dp21/icesheet/dp21_fit_icesheet.py'


project:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: ""
    script: "dp21_project_icesheet.py"
    options:
      - "nsamps"
      - "pyear_start"
      - "pyear_end"
      - "pyear_step"
      - "seed"
      - "replace"
      - "pipeline_id"
    upload_input_data:
      - './modules/dp21/icesheet/dp21_project_icesheet.py'
    copy_input_data:
      pre-process:
        task1:
          - "%PIPELINE_ID%_data.pkl"
    global_total_files:
      - "%PIPELINE_ID%_AIS_globalsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_EAIS_globalsl.nc"
      - "%PIPELINE_ID%_WAIS_globalsl.nc"
      - "%PIPELINE_ID%_AIS_globalsl.nc"
#      - "%PIPELINE_ID%_projections.pkl"

post-process:
  task1:
    executable: "python3"
    cpu:
      processes: 1
      process-type: None
      threads-per-process: 1
      thread-type: None
    pre_exec: "tar -xzf dp21_icesheet_postprocess_data.tgz; rm dp21_icesheet_postprocess_data.tgz"
    script: "dp21_postprocess_icesheet.py"
    options:
      - "chunksize"
      - "locationfile"
      - "pipeline_id"
    upload_input_data:
      - './modules/dp21/icesheet/dp21_postprocess_icesheet.py'
      - './modules/dp21/icesheet/read_locationfile.py'
      - './modules/dp21/icesheet/AssignFP.py'
      - './modules/dp21/icesheet/ReadFingerprint.py'
      - './modules/dp21/icesheet/data/dp21_icesheet_postprocess_data.tgz'
    copy_shared_data:
      - '$SHARED/location.lst'
    copy_input_data:
      project:
        task1:
          - "%PIPELINE_ID%_projections.pkl"
    local_total_files:
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
    download_output_data:
      - "%PIPELINE_ID%_WAIS_localsl.nc"
      - "%PIPELINE_ID%_EAIS_localsl.nc"
